TrajectoryPlannerROS:
  max_vel_x: 1.9
  min_vel_x: 0.1
  max_vel_theta: 2
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 2
  acc_lim_x: 2

  holonomic_robot: false

  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.03

  # More parameters: see base_local_planner documentation online
