DWAPlannerROS: 
  # Robot configuration parameters
  max_vel_trans: 1
  min_vel_trans: 0
  max_vel_x: 1
  min_vel_x: -1
  max_vel_y: 0
  min_vel_y: 0
  max_vel_theta: 1
  min_vel_theta: -1

  acc_lim_theta: 1
  acc_lim_trans: 1
  acc_lim_x: 1
  acc_lim_y: 0


  # Goal tolerance parameters
  #xy_goal_tolerance: 1

  # Forward simulation parameters
  sim_time: 1.7 #1.7
  vx_samples: 5
  vy_samples: 0
  vth_samples: 10

  #Trajectory scoring parameters
  path_distance_bias: 32 #32
  goal_distance_bias: 24 #24
  # stop_time_buffer: .05 #0.2
  scaling_speed: 1 #0.25


  # Oscillation prevention parameters

  # Global plan parameters  
