TebLocalPlannerROS:
  # Robot configuration parameters
  max_vel_x: 1
  max_vel_backwards: 1
  max_vel_y: 0
  max_vel_theta: 1

  acc_lim_theta: 1
  acc_lim_x: 1
  acc_lim_y: 0

  footprint_model/type: polygon
  footprint_model/vertices: [[-0.220, -0.275], [-0.220, 0.275], [0.525, 0.275], [0.525, -0.275]]
  min_obstacle_dist: .05
  inflation_distance: 0.2
  # Goal tolerance parameters

  # Forward simulation parameters

  #Trajectory scoring parameters

  # Oscillation prevention parameters

  # Global plan parameters  
